### ISSUE TITLE
Lavar los platos

### ISSUE THREAD

**Issue by lukascorr** [Pupa23/VisionWeb#2]
Que queden bien limpitos.

**Comment by lukascorr** [comment]
¡Task Completed! Very Good !
![lava-platos.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad51d13dde96f00110bf464/125516c66e82c728ace21e0d46e4958c22cf93a58efdb050e611b2843b492d762a10e17132d0e27dea177f51090e18f9145d5c44fcf8db78f2e76871834e17ff933c0120996048e6edc00db513bb27814e80b4ba8b49c8ee3426e58b8f5d73.jpg)

**Comment by matu00** [comment]
JAJJAJAJAJAJAJ SOS UN PAJERO!!!


2018-05-12 17:59 GMT-03:00 Lucas Correa <notifications@github.com>:
